janus(1)

# NAME

janus - compare two files line by line

# SYNOPSIS

*janus* [OPTIONS]... FILES

# DESCRIPTION

*janus* is a simple and easy-to-use command-line utility for comparing files and
finding differences between them.

# OPTIONS

*--no-color*
	Output a diff without colors.

*-h*, *--help*
	Show help message and quit.

*-v*, *--version*
	Show version number and quit.

# AUTHORS

Maintained by James Pond <james@cipher.host>.
